[settings]
drift_email_receiver = ['example@gmail.com']
project_name = 'model-decay-monitor'

[data]
data_path = 'df_wine.csv'
response = 'wine_colour'
positive_class = 'white'

[model_monitor]
model_path = './src/data/models/lasso_model.sav'
reference_data_path = './src/data/assets/df_day1.pickle'
column_mapping = [{'target' = 'wine_colour',
                  'prediction' = 'prediction',
                  'datetime' = [],
                  'numerical_features' = ['fixed acidity',
                                         'volatile acidity',
                                         'citric acid',
                                         'residual sugar',
                                         'chlorides',
                                         'free sulfur dioxide',
                                         'total sulfur dioxide',
                                         'density',
                                         'pH',
                                         'sulphates',
                                         'alcohol',
                                         'quality'],
                   'categorical_features' = []}]

[json_reports_path]
latest_drift_report_json = './reports/{today}/model_data_drift_poc_report_{today}.json'

[message]

[result]